export const API_BASE_URL = process.env.API_BASE_URL;
export const DATETIME_FORMAT = 'MM/DD/YYYY, h:mm:ss a';
export const ALL_SYMBOLS = [
  { symbol: 'USD', label: 'US dollar' },
  { symbol: 'JPY', label: 'Japanese yen' },
  { symbol: 'BGN', label: 'Bulgarian lev' },
  { symbol: 'CZK', label: 'Czech koruna' },
  { symbol: 'DKK', label: 'Danish krone	' },
  { symbol: 'GBP', label: 'Pound sterling	' },
  { symbol: 'HUF', label: 'Hungarian forint	' },
  { symbol: 'PLN', label: 'Polish zloty	' },
  { symbol: 'RON', label: 'Romanian leu	' },
  { symbol: 'SEK', label: 'Swedish krona	' },
  { symbol: 'CHF', label: 'Swiss franc' },
  { symbol: 'ISK', label: 'Icelandic krona' },
  { symbol: 'NOK', label: 'Norwegian krone' },
  { symbol: 'HRK', label: 'Croatian kuna	' },
  { symbol: 'RUB', label: 'Russian rouble' },
  { symbol: 'TRY', label: 'Turkish lira' },
  { symbol: 'AUD', label: 'Australian dollar' },
  { symbol: 'BRL', label: 'Brazilian real	' },
  { symbol: 'CAD', label: 'Canadian dollar	' },
  { symbol: 'CNY', label: 'Chinese yuan renminbi	' },
  { symbol: 'HKD', label: 'Hong Kong dollar	' },
  { symbol: 'IDR', label: 'Indonesian rupiah	' },
  { symbol: 'ILS', label: 'Israeli shekel	' },
  { symbol: 'INR', label: 'Indian rupee	' },
  { symbol: 'KRW', label: 'South Korean won	' },
  { symbol: 'MXN', label: 'Mexican peso	' },
  { symbol: 'MYR', label: 'Malaysian ringgit	' },
  { symbol: 'NZD', label: 'New Zealand dollar' },
  { symbol: 'PHP', label: 'Philippine peso	' },
  { symbol: 'SGD', label: 'Singapore dollar	' },
  { symbol: 'THB', label: 'Thai baht	' },
  { symbol: 'ZAR', label: 'South African rand' },
];
